CategoryOrder = [
	"General Controls",
	"Viewing Controls",
	"Depiction",
	"Structure Analysis",
	"Structure Comparison",
	'Sequence',
	"Surface/Binding Analysis",
	"Structure Editing",
	"Amber",
	"MD/Ensemble Analysis",
	"Higher-Order Structure",
	"Volume Data",
	"Demos",
	"Movement",
	"Utilities",
]

ToolOrder = {
	"Demos": [
		"COX Inhibitors Demo",
		"Hormone-Receptor Complex Demo",
		"Demo Editor",
		"About Demos",
	],
	"Depiction": [
		"Color Secondary Structure",
		"Rainbow",
		"PipesAndPlanks",
		"Nucleotides",
		"Render by Attribute",
		"2D Labels",
		"Color Actions",
		"Ribbon Style Editor",
		"Surface Capping",
		"Per-Model Clipping",
		'Color Zone',
		"MainChain",
		"PseudoBond Reader",
		"Color Key"
	],
	"General Controls": [
		"Command Line",
		"Model Panel",
		"PseudoBond Panel",
		"Keyboard Shortcuts",
		"Task Panel",
		"IDLE",
	],
	"Higher-Order Structure": [
		"Multiscale Models",
		"Unit Cell",
		'Crystal Contacts',
		'Small-Angle X-Ray Profile',
		"Scale Bar",
		"Icosahedron Surface",
		'Flatten Icosahedron',
                'Cage Builder',
	],
	"MD/Ensemble Analysis": [
		"MD Movie",
		"Ensemble Cluster",
		"Ensemble Match",
		"Tile Structures",
		"Calculate Normal Modes",
		"Molecular Dynamics Simulation",
	],
	"Movement": [
		"Rotation",
		"Undo Move",
		"Redo Move",
		'Movement Mouse Mode',
		"Constrained Move",
		'Transform Coordinates',
	],
	"Sequence": [
		"Sequence",
		"PDB/UniProt Info",
		"Multalign Viewer",
		"Match -> Align",
		"Blast Protein",
		"Align Chain Sequences"
	],
	"Structure Analysis": [
		"FindHBond",
		"Find Clashes/Contacts",
		"Sequence",
		"Distances",
		"Angles/Torsions",
		"Metal Geometry",
		"Axes/Planes/Centroids",
		"Thermal Ellipsoids",
		"Adjust Torsions",
		"Render by Attribute",
		"Define Attribute",
		"Calculate Normal Modes",
		"Attribute Calculator",
		"ResProp",
	],
	"Structure Comparison": [
		"MatchMaker",
		"Multalign Viewer",
		"Match -> Align",
		"Morph Conformations",
		"RR Distance Maps",
		"Ensemble Cluster",
		"Ensemble Match",
		"Tile Structures",
		"Minrms Plot",
	],
	"Structure Editing": [
		"AddH",
		"Add Charge",
		"Dock Prep",
		"PDB2PQR",
		"Rotamers",
		"Adjust Torsions",
		"Build Structure",
		"Model/Refine Loops",
                "Movement Mouse Mode",
		"Minimize Structure",
		"Add Ions",
		"Solvate",
		"Write DMS",
		"Change Chain IDs",
		"Renumber Residues",
	],
	"Surface/Binding Analysis": [
		"FindHBond",
		"Find Clashes/Contacts",
		"Electrostatic Surface Coloring",
		"Coulombic Surface Coloring",
		"APBS",
		"Surface Capping",
		"Surface Zone",
		"ViewDock",
		"Dock Prep",
		"AutoDock Vina",
		"Measure Volume and Area",
		"Area/Volume from Web",
		"Measure and Color Blobs",
		'Intersurf',
		"Surfnet",
		"DelPhiController",
		"HearDock",
	],
	"Utilities": [
		"Reply Log",
		"2D Labels",
		"Notepad",
		"Movie Recorder",
		"Color Key",
		"Animation",
		"Structure Diagram",
		"Browser Configuration",
		"Benchmark",
		"Color Editor",
		"Palette Editor",
		"2D Texture",
		"ReadStdin",
		"RESTServer",
		"Debug Graphics Driver",
	],
	"Viewing Controls": [
		"Side View",
		"Camera",
		"Effects",
		"Lighting",
		"Shininess",
	],
	"Volume Data": [
		'Volume Viewer',
		'Fit in Map',
                'Fit List',
		'Surface Color',
		'Color Zone',
		'Morph Map',
		'Volume Tracer',
		'Volume Filter',
		'Hide Dust',
		'Segger',
		'SegFit',
                'MapQ from Segger',
		'MultiFit',
		'Volume Eraser',
		'Measure Volume and Area',
		'Measure and Color Blobs',
		'Volume Mean, SD, RMS',
		'Values at Atom Positions',
		'Volume Series',
		'Phantom Force Feedback',
		'Volume Menu on Menubar',
	],
}
