#
# ---  movie licence agreement ---
#

MOVIE_LICENSE = 'Movie License'
MOVIE_LICENSE_TEXT = '''Legal Disclaimer - Proprietary Media Formats

Two of the video formats (MPEG-2 and MPEG-4) supported by Chimera's movie
features are encoded using proprietary algorithms which are protected by
patents. The MPEG-LA (licensing authority, http://www.mpeg-la.com) is the
organization responsible for collecting royalties on MPEG-related technologies.

Anyone who intends to use these technologies for commercial purposes is required
by law to pay the appropriate fees to the licensing authority. While there has
been no precedent of legal action taken against those who utilize these
technologies for personal use, this can still be construed as a violation of the
patent and may be subject to legal action. Chimera uses third party software
called FFmpeg (http://ffmpeg.sourceforge.net) to handle video encoding.  More
information on legal issues associated with using this software can be found in
the Frequently Asked Questions section of their Web site.

By using Chimera's movie features, you assume full responsibility for any
royalties that might be due as a result of utilizing this patented
technology.'''

MOVIE_LICENSE_HTML = '''<font size=12><b> Legal Disclaimer - Proprietary Media Formats</b></font>
<p>Two of the video formats (MPEG-2 and MPEG-4) supported by Chimera's
movie features are encoded using proprietary algorithms which are protected
by patents. The <a href='http://www.mpeg-la.com'>MPEG-LA</a> (licensing
authority) is the organization responsible for collecting royalties on
MPEG-related technologies.</p>
<p>Anyone who intends to use these technologies for commercial purposes is
required by law to pay the appropriate fees to the licensing authority. While
there has been no precedent of legal action taken against those who utilize
these technologies for personal use, this can still be construed as a violation
of the patent and may be subject to legal action. Chimera uses third party
software called <a href='http://ffmpeg.sourceforge.net'>FFmpeg</a> to handle
video encoding.  More information on legal issues associated with using this
software can be found in the
<a href='http://ffmpeg.sourceforge.net/legal.php'>Frequently Asked Questions</a>
section of their Web site.</p>
<p>By using Chimera's movie features, you assume full responsibility
for any royalties that might be due as a result of utilizing this
patented technology.</p>'''

from chimera.baseDialog import ModalDialog
class AcceptLicenseDialog(ModalDialog):
        title = "Accept MPEG License"
        buttons = ('Accept', 'Decline')
        provideStatus = False
        def fillInUI(self, parent):
                import Tkinter
                import Pmw
                license_lbl = Tkinter.Label(parent,
                                            text="You must read and accept the following agreement before\n" \
                                                "using Chimera's movie features:",
                                            justify='left'
                                            )
                license_lbl.grid(row=0, column=0, sticky='w', pady=5)
                from chimera.HtmlText import HtmlText
                self.infoText = Pmw.ScrolledText(parent,
                                                 text_pyclass=HtmlText,
                                                 text_relief='sunken',
                                                 text_wrap='word',
                                                 text_width=50,
                                                 text_height=8
                                                 )
                self.infoText.settext(MOVIE_LICENSE_HTML)
                self.infoText.configure(text_state='disabled',
                                        hscrollmode='dynamic',
                                        vscrollmode='dynamic',
                                        text_background=parent.cget('background')
                                        )
                self.infoText.grid(row=1, column=0, sticky='nsew', pady=5)
                parent.rowconfigure(1, weight=1)
                parent.columnconfigure(0, weight=1)
        def Accept(self):
                ModalDialog.Cancel(self, value=True)
        def Decline(self):
                ModalDialog.Cancel(self, value=False)

movie_license_prefs = None
def acceptLicense():

        MOVIE_LICENSE_AGREE = 'accept MPEG license'
        global movie_license_prefs
        if movie_license_prefs is None:
                # Inherit license agreement value from prior hidden category
                # generated by Movie Recorder.
                inheritMovieRecorder = (MOVIE_LICENSE_AGREE,
                                        'Movie Recorder',
                                        'accepted license agreement',
                                        None)
                from chimera import preferences
                movie_license_prefs = preferences.addCategory(MOVIE_LICENSE,
                                              preferences.HiddenCategory,
                                              inherit= [ inheritMovieRecorder ],
                                              optDict = { MOVIE_LICENSE_AGREE: False },
                                              )

        if not movie_license_prefs[MOVIE_LICENSE_AGREE]:
                import chimera
                if chimera.nogui:
                        # Continue, without updating the license agreement
                        return True
                dlg = AcceptLicenseDialog()
                movie_license_prefs[MOVIE_LICENSE_AGREE] = dlg.run(chimera.tkgui.app)
        return movie_license_prefs[MOVIE_LICENSE_AGREE]
